language: node_js
node_js:
  - "11"
cache: yarn
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
install:
  - yarn --ignore-engines
  - yarn patch-package
jobs:
  include:
    - stage: github build
      script: POI_PATH=/qr-packets-demo yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: gh-pages
        local-dir: dist
        on:
          branch: master
    - stage: duxi build
      script:
        - POI_PATH=/cold yarn build
        - git show -s --pretty=%H > ./dist/gitrev
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: gh-pages-cold
        local-dir: dist
        on:
          branch: master
    - stage: icewall build
      script:
        - POI_PATH=/ yarn build
        - git show -s --pretty=%H > ./dist/gitrev
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: gh-pages-ice
        local-dir: dist
        on:
          branch: ice-wall
